[theme]
primaryColor = "#0284c7"
backgroundColor = "#0b0f17"
secondaryBackgroundColor = "#151e2e"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
